"use client";

import * as DialogPrimitive from "@radix-ui/react-dialog";
import * as TabsPrimitive from "@radix-ui/react-tabs";
import { Slot } from "@radix-ui/react-slot";
import { cva, type VariantProps } from "class-variance-authority";
import { AlertCircle, LoaderCircle, X } from "lucide-react";
import type { ButtonHTMLAttributes, HTMLAttributes, ReactNode } from "react";
import { cn } from "@/lib/utils";

const buttonVariants = cva("inline-flex items-center justify-center rounded-lg text-sm font-semibold transition-colors disabled:pointer-events-none disabled:opacity-50 focus-visible:outline-none", { variants: { variant: { default: "bg-[var(--primary)] text-[var(--primary-foreground)] hover:opacity-90", secondary: "bg-slate-100 text-slate-900 hover:bg-slate-200 dark:bg-slate-800 dark:text-slate-100", outline: "border bg-transparent hover:bg-slate-100 dark:hover:bg-slate-800", ghost: "hover:bg-slate-100 dark:hover:bg-slate-800" }, size: { default: "h-10 px-4", sm: "h-8 px-3 text-xs", lg: "h-11 px-6" } }, defaultVariants: { variant: "default", size: "default" } });
export function Button({ className, variant, size, asChild = false, ...props }: ButtonHTMLAttributes<HTMLButtonElement> & VariantProps<typeof buttonVariants> & { asChild?: boolean }) { const Component = asChild ? Slot : "button"; return <Component className={cn(buttonVariants({ variant, size }), className)} {...props} />; }
export function Input({ className, ...props }: React.InputHTMLAttributes<HTMLInputElement>) { return <input className={cn("h-10 w-full rounded-lg border bg-transparent px-3 text-sm placeholder:text-slate-400", className)} {...props} />; }
export function Textarea({ className, ...props }: React.TextareaHTMLAttributes<HTMLTextAreaElement>) { return <textarea className={cn("min-h-24 w-full rounded-lg border bg-transparent p-3 text-sm placeholder:text-slate-400", className)} {...props} />; }
export function Card({ className, ...props }: HTMLAttributes<HTMLDivElement>) { return <section className={cn("rounded-xl border bg-[var(--card)] shadow-sm", className)} {...props} />; }
export function Badge({ className, children, ...props }: HTMLAttributes<HTMLSpanElement>) { return <span className={cn("inline-flex items-center rounded-full bg-teal-50 px-2.5 py-1 text-xs font-semibold text-teal-800 dark:bg-teal-950 dark:text-teal-200", className)} {...props}>{children}</span>; }
export function Avatar({ name, className }: { name: string; className?: string }) { return <div aria-label={name} className={cn("flex size-9 items-center justify-center rounded-full bg-teal-700 text-sm font-bold text-white", className)}>{name.split(" ").map((part) => part[0]).slice(0, 2).join("")}</div>; }
export function Skeleton({ className }: { className?: string }) { return <div aria-hidden="true" className={cn("animate-pulse rounded-md bg-slate-200 dark:bg-slate-800", className)} />; }
export function Spinner({ label = "Loading" }: { label?: string }) { return <span role="status" className="inline-flex items-center gap-2 text-sm text-[var(--muted)]"><LoaderCircle className="size-4 animate-spin" />{label}</span>; }
export function Progress({ value }: { value: number }) { return <div aria-label={`${Math.round(value)}% complete`} className="h-2 overflow-hidden rounded-full bg-slate-100 dark:bg-slate-800"><div className="h-full rounded-full bg-[var(--primary)] transition-all" style={{ width: `${Math.max(0, Math.min(value, 100))}%` }} /></div>; }
export function MetricCard({ label, value, detail }: { label: string; value: string; detail: string }) { return <Card className="p-5"><p className="text-sm text-[var(--muted)]">{label}</p><p className="mt-2 text-3xl font-bold tracking-tight">{value}</p><p className="mt-2 text-sm text-[var(--muted)]">{detail}</p></Card>; }
export function ScoreRing({ score, label = "Career Health" }: { score: number; label?: string }) { const bounded = Math.max(0, Math.min(score, 100)); return <div aria-label={`${label}: ${bounded} out of 100`} className="flex size-28 flex-col items-center justify-center rounded-full border-8 border-teal-500 bg-teal-50 text-center dark:bg-teal-950"><span className="text-2xl font-bold">{bounded}</span><span className="text-xs text-[var(--muted)]">{label}</span></div>; }
export function StatusBadge({ status }: { status: "strong" | "developing" | "at_risk" }) { const labels = { strong: "Strong", developing: "Developing", at_risk: "At risk" }; const styles = { strong: "bg-emerald-50 text-emerald-800 dark:bg-emerald-950 dark:text-emerald-200", developing: "bg-amber-50 text-amber-800 dark:bg-amber-950 dark:text-amber-200", at_risk: "bg-red-50 text-red-800 dark:bg-red-950 dark:text-red-200" }; return <Badge className={styles[status]}>{labels[status]}</Badge>; }
export function EmptyState({ title, description, action }: { title: string; description: string; action?: ReactNode }) { return <Card className="flex flex-col items-center p-10 text-center"><h2 className="font-semibold">{title}</h2><p className="mt-2 max-w-md text-sm text-[var(--muted)]">{description}</p>{action ? <div className="mt-5">{action}</div> : null}</Card>; }
export function ErrorState({ title = "Something went wrong", description = "Please try again." }: { title?: string; description?: string }) { return <Card role="alert" className="border-red-200 p-5"><div className="flex gap-3"><AlertCircle className="size-5 text-red-600" /><div><h2 className="font-semibold">{title}</h2><p className="mt-1 text-sm text-[var(--muted)]">{description}</p></div></div></Card>; }
export function LoadingState({ label = "Loading content" }: { label?: string }) { return <Card className="p-6"><Spinner label={label} /></Card>; }
export function ActionCard({ title, description, action }: { title: string; description: string; action: string }) { return <Card className="p-5"><h3 className="font-semibold">{title}</h3><p className="mt-2 text-sm text-[var(--muted)]">{description}</p><p className="mt-4 text-sm font-semibold text-teal-700 dark:text-teal-300">Next: {action}</p></Card>; }
export function ReasonList({ reasons }: { reasons: string[] }) { return <ul className="space-y-2 text-sm text-[var(--muted)]">{reasons.map((reason) => <li key={reason} className="flex gap-2"><span className="text-teal-600">•</span>{reason}</li>)}</ul>; }
export const Tabs = TabsPrimitive.Root; export const TabsList = TabsPrimitive.List; export const TabsTrigger = TabsPrimitive.Trigger; export const TabsContent = TabsPrimitive.Content;
export function DataTable({ children }: { children: ReactNode }) { return <div className="overflow-x-auto rounded-xl border"><table className="w-full text-left text-sm">{children}</table></div>; }
export function Dialog({ title, children, trigger }: { title: string; children: ReactNode; trigger: ReactNode }) { return <DialogPrimitive.Root><DialogPrimitive.Trigger asChild>{trigger}</DialogPrimitive.Trigger><DialogPrimitive.Portal><DialogPrimitive.Overlay className="fixed inset-0 bg-slate-950/40" /><DialogPrimitive.Content className="fixed left-1/2 top-1/2 w-[min(92vw,32rem)] -translate-x-1/2 -translate-y-1/2 rounded-xl bg-[var(--card)] p-6 shadow-xl"><DialogPrimitive.Title className="font-semibold">{title}</DialogPrimitive.Title><DialogPrimitive.Close aria-label="Close dialog" className="absolute right-4 top-4"><X className="size-4" /></DialogPrimitive.Close><div className="mt-4">{children}</div></DialogPrimitive.Content></DialogPrimitive.Portal></DialogPrimitive.Root>; }
export function Drawer({ title, children }: { title: string; children: ReactNode }) { return <aside aria-label={title} className="rounded-xl border bg-[var(--card)] p-4"><h2 className="font-semibold">{title}</h2><div className="mt-3">{children}</div></aside>; }
export function Select({ className, ...props }: React.SelectHTMLAttributes<HTMLSelectElement>) { return <select className={cn("h-10 w-full rounded-lg border bg-transparent px-3 text-sm", className)} {...props} />; }
export function SectionHeader({ title, description }: { title: string; description?: string }) { return <div><h2 className="text-lg font-semibold tracking-tight">{title}</h2>{description ? <p className="mt-1 text-sm text-[var(--muted)]">{description}</p> : null}</div>; }
export function PageHeader({ title, description, action }: { title: string; description: string; action?: ReactNode }) { return <div className="mb-8 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-semibold text-teal-700 dark:text-teal-300">CareerPilot OS</p><h1 className="mt-1 text-3xl font-bold tracking-tight">{title}</h1><p className="mt-2 max-w-2xl text-[var(--muted)]">{description}</p></div>{action}</div>; }
