"""Pydantic request and response models for deterministic demo features."""

from pydantic import BaseModel, ConfigDict, Field


class DemoResumeRequest(BaseModel):
    """Validate raw resume text submitted to a deterministic demo endpoint.

    Attributes:
        resume_text: Extracted resume text to analyze.
    """

    model_config = ConfigDict(extra="forbid", str_strip_whitespace=True)

    resume_text: str = Field(
        min_length=1,
        max_length=100_000,
        description="Raw text extracted from a candidate resume.",
    )


class ATSSectionScores(BaseModel):
    """Provide deterministic ATS scores for individual resume sections.

    Attributes:
        skills: Score for demonstrated technical and professional skills.
        experience: Score for work history evidence.
        education: Score for education information.
        projects: Score for projects and outcomes.
        keywords: Score for role-relevant terminology.
    """

    model_config = ConfigDict(extra="forbid")

    skills: int = Field(ge=0, le=100)
    experience: int = Field(ge=0, le=100)
    education: int = Field(ge=0, le=100)
    projects: int = Field(ge=0, le=100)
    keywords: int = Field(ge=0, le=100)


class ATSResponse(BaseModel):
    """Represent a deterministic, structured ATS analysis result.

    Attributes:
        overall_score: Weighted summary score for the submitted resume.
        section_scores: Scores for individual resume sections.
        strengths: Concrete evidence-based positives.
        improvements: Practical recommendations for improving the resume.
    """

    model_config = ConfigDict(extra="forbid")

    overall_score: int = Field(ge=0, le=100)
    section_scores: ATSSectionScores
    strengths: list[str] = Field(min_length=3, max_length=3)
    improvements: list[str] = Field(min_length=3, max_length=3)


class JobMatch(BaseModel):
    """Describe one deterministic career recommendation.

    Attributes:
        title: Career title.
        match: Percentage match based on detected resume evidence.
        salary: Indicative United Kingdom salary range.
        reason: Concise explanation grounded in detected keywords.
    """

    model_config = ConfigDict(extra="forbid")

    title: str = Field(min_length=1, max_length=100)
    match: int = Field(ge=0, le=100)
    salary: str = Field(min_length=1, max_length=50)
    reason: str = Field(min_length=1, max_length=300)


class InterviewPrep(BaseModel):
    """Group interview questions generated by the deterministic demo service.

    Attributes:
        technical: Questions covering demonstrated technical capabilities.
        behavioral: Questions assessing collaboration and delivery behaviours.
        resume_questions: Questions that clarify specific resume evidence.
    """

    model_config = ConfigDict(extra="forbid")

    technical: list[str] = Field(min_length=3, max_length=3)
    behavioral: list[str] = Field(min_length=3, max_length=3)
    resume_questions: list[str] = Field(min_length=3, max_length=3)
